version: 2
updates:
- package-ecosystem: 'composer'
  directory: '/'
  schedule:
    interval: 'weekly'
  cooldown:
    default-days: 1
  ignore:
    - dependency-name: '**'
      update-types: ['version-update:semver-major']
  versioning-strategy: increase
  groups:
    security-updates:
      applies-to: security-updates
      dependency-type: production
    dependencies:
      applies-to: version-updates
      dependency-type: production
      update-types:
        - minor
        - patch
    phpstan-dependencies:
      applies-to: version-updates
      dependency-type: development
      update-types:
        - minor
        - patch
      patterns:
        - 'phpstan/*'
  open-pull-requests-limit: 5
  labels:
    - 'backend'
    - 'dependencies'
  assignees:
    - chapter-backend
  target-branch: "main"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 5
  target-branch: "main"
